BASE_PATH: "/home/heigatvu/MyFile/my-project/ADReSSo-feature-extraction"

OUTPUT_TRADITIONAL_FEATURE_PATH: "${BASE_PATH}/output/traditionalFeatures"

TOP_K_FEATURE_PATH: "${BASE_PATH}/output/top_k_features"

# Extract transcripts
TRANSCRIPT_PATH: "${BASE_PATH}/output/transcripts"

# PKL files
PKL_TRADITIONAL_PATH: "${BASE_PATH}/output/pkl/traditionalFeatures"

train:
    CSV_SEGMENT_TRAIN_PATH: "${BASE_PATH}/data/diagnosis/train/segmentation"
    AUDIO_TRAIN_PATH: "${BASE_PATH}/data/diagnosis/train/audio"
    MMSE_DIAG_TRAIN_PATH: "${BASE_PATH}/data/diagnosis/train/adresso-train-mmse-scores.csv"

test:
    CSV_SEGMENT_TEST_PATH: "${BASE_PATH}/data/diagnosis/test-dist/segmentation"
    AUDIO_TEST_PATH: "${BASE_PATH}/data/diagnosis/test-dist/audio"
    MMSE_DIAG_TEST_PATH: "${BASE_PATH}/data/diagnosis/test-dist/adresso-test-mmse-scores.csv"

output_model:
    TRADITIONAL_MODEL_PATH: "${BASE_PATH}/output/results/traditional"